name: Replicate PUSH

on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: 'Source branch to copy Tekton files from'
        required: true
        default: 'rhoai-x.y'
      target_branch:
        description: 'Target branch to copy Tekton files to'
        required: true
        default: 'rhoai-x.y'
      version:
        description: 'Version to update in Tekton files (e.g., v2.16.0)'
        required: true
        default: 'vx.y.z'

permissions:
  contents: write

jobs:
  copy-push-tekton-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Automation Repository
        uses: actions/checkout@v3
        with:
          path: automation_repo
          token: ${{ secrets.PARAMETER_TOKEN }}

      - name: Process Repositories
        run: |
          set -e

          SOURCE_BRANCH=${{ github.event.inputs.source_branch }}
          TARGET_BRANCH=${{ github.event.inputs.target_branch }}
          VERSION=${{ github.event.inputs.version }}

          if [[ "$VERSION" =~ v([0-9]+)\.([0-9]+)\.([0-9]+) ]]; then
            major="${BASH_REMATCH[1]}"
            minor="${BASH_REMATCH[2]}"
          else
            echo "Error: Invalid version format."
            exit 1
          fi

          while IFS= read -r repo_url; do
            if [[ -z "$repo_url" || "$repo_url" =~ ^# ]]; then
              continue
            fi

            repo_name=$(basename "$repo_url" .git)
            echo "Processing repository: $repo_url"

            git clone "$repo_url"
            cd "$repo_name" || exit

            if ! git checkout "$SOURCE_BRANCH"; then
              echo "Source branch $SOURCE_BRANCH does not exist."
              cd ..
              rm -rf "$repo_name"
              continue
            fi

            mkdir -p ../tekton_copy_$repo_name

            # Process push files
            for file in .tekton/*push*.yaml; do
              if [ -f "$file" ]; then
                file_name=$(basename "$file")
                new_file_name=$(echo "$file_name" | sed "s/[0-9]\+-[0-9]\+/${major}-${minor}/g" | sed "s/v[0-9]*\.[0-9]*\.[0-9]*/$VERSION/")
                if [[ "$file_name" != "$new_file_name" ]]; then
                  mv "$file" "../tekton_copy_$repo_name/$new_file_name"
                  echo "Renamed file from $file_name to $new_file_name"
                else
                  cp "$file" "../tekton_copy_$repo_name/$file_name"
                  echo "No renaming needed for $file_name"
                fi
              fi
            done

            if ! git checkout "$TARGET_BRANCH"; then
              git checkout -b "$TARGET_BRANCH"
            fi

            cp -r ../tekton_copy_$repo_name/* .tekton/

            git add .tekton
            git commit -m "Sync push Tekton files from $SOURCE_BRANCH to $TARGET_BRANCH with version updates"
            git push origin "$TARGET_BRANCH"

            cd ..
            rm -rf "$repo_name" "tekton_copy_$repo_name"
          done < automation_repo/repos.txt
